<a href="https://colab.research.google.com/github/RajSimpi9988/Algo-Based-Projects-/blob/main/Sudoku_Solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sudoku Solver


In [19]:
# Importing the basic libraries

import numpy as np

The 9x9 Grid 

In [30]:
grid = [[0,8,0,5,4,2,0,7,6],
        [0,0,7,0,6,9,0,8,0],
        [4,0,0,8,0,0,2,0,5],
        [9,0,0,6,3,5,0,0,4],
        [3,4,6,0,8,0,5,9,7],
        [0,0,5,9,7,4,6,0,3],
        [0,3,8,0,0,6,0,0,9],
        [6,1,0,4,9,3,7,5,8],
        [7,9,4,0,5,8,3,6,0]]

In [31]:
print (np.matrix(grid))

[[0 8 0 5 4 2 0 7 6]
 [0 0 7 0 6 9 0 8 0]
 [4 0 0 8 0 0 2 0 5]
 [9 0 0 6 3 5 0 0 4]
 [3 4 6 0 8 0 5 9 7]
 [0 0 5 9 7 4 6 0 3]
 [0 3 8 0 0 6 0 0 9]
 [6 1 0 4 9 3 7 5 8]
 [7 9 4 0 5 8 3 6 0]]


Defining the possible moves

In [32]:
def possible(row, coloumn, number):
  global grid
  # number appearance in the given row 
  for i in range(0,9):
    if grid[row][i] == number:
      return False
  
  # number appearance in the given column
  for i in range(0,9):
    if grid[i][coloumn] == number:
      return False

  # number appearance in the given 3x3 nonet

  x0 = (coloumn // 3) * 3
  y0 = (row // 3) *3
  for i in range(0,3):
    for j in range(0,3):
      if grid[y0+i][x0+j] == number:
        return False 
  return True 

Defining the legal moves 

In [37]:
def solve():
    global grid
    for row in range(0,9):
      for coloumn in range (0,9):
        if grid[row][coloumn] == 0:
          for number in range(1,10):
            if possible(row, coloumn, number):
                grid[row][coloumn] = number
                solve()
                grid[row][coloumn]= 0
          return

    print (np.matrix(grid))
solve()

[[1 8 3 5 4 2 9 7 6]
 [2 5 7 3 6 9 4 8 1]
 [4 6 9 8 1 7 2 3 5]
 [9 7 1 6 3 5 8 2 4]
 [3 4 6 2 8 1 5 9 7]
 [8 2 5 9 7 4 6 1 3]
 [5 3 8 7 2 6 1 4 9]
 [6 1 2 4 9 3 7 5 8]
 [7 9 4 1 5 8 3 6 2]]
