<a href="https://colab.research.google.com/github/RajSimpi9988/Algo-Based-Projects-/blob/main/Sudoku_Solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sudoku Solver


In [19]:
# Importing the basic libraries

import numpy as np

The 9x9 Grid 

In [27]:
grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,0,0]]

In [21]:
print (np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 0 0]]


Defining the possible moves

In [22]:
def possible(row, coloumn, number):
  global grid
  # number appearance in the given row 
  for i in range(0,9):
    if grid[row][i] == number:
      return False
  
  # number appearance in the given column
  for i in range(0,9):
    if grid[i][coloumn] == number:
      return False

  # number appearance in the given 3x3 nonet

  x0 = (coloumn // 3) * 3
  y0 = (row // 3) *3
  for i in range(0,3):
    for j in range(0,3):
      if grid[y0+i][x0+j] == number:
        return False 
  return True 

Defining the legal moves 

In [28]:
def solve():
    global grid
    for row in range(0,9):
      for coloumn in range (0,9):
        if grid[row][coloumn] == 0:
          for number in range(1,10):
            if possible(row, coloumn, number):
                grid[row][coloumn] = number
                solve()
                grid[row][coloumn]= 0
          return

    print (np.matrix(grid))
    input('More Posiible Solutions')

solve()

[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
More Posiible Solutions10
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
More Posiible Solutions5
